### ISSUE TITLE
手型检测，如果我只想检测左手的手型

### ISSUE THREAD

**Issue by junpingfu** [XanderXu/HandVector#1]
手型检测，如果我只想检测左手的手型，是将例子中的
latestHandTracking.right相关的代码移除吗

**Comment by XanderXu** [comment]
不是的，你需要移除这句：
```swift
let rightScore = model.latestHandTracking.rightHandVector?.similarity(of: HandVectorMatcher.allFingers, to: leftOKVector)
```
这样就不再计算右手与目标的相似度。其中 `leftOKVector` 是目标手势，`model.latestHandTracking.rightHandVector` 是当前右手的位置向量。

`latestHandTracking.right` 中的 `.right`  中包含的是显示用的可视化 ModelEntity，用来显示关节处的小球及处理物理碰撞。

**Comment by junpingfu** [comment]
谢谢指导。
我尝试修改
guard let okVector = model.handEmojiDict["🤚"]?.convertToHandVectorMatcher(), let leftOKVector = okVector.left else { return }
替换不同手型，然而分数显示，还是只能识别出👌的手势，看了HandEmojiTotalJson.json中，已经有配置了这个手型。不知道是不是还有其他地方需要修改呢？

**Comment by XanderXu** [comment]
> 谢谢指导。 我尝试修改 guard let okVector = model.handEmojiDict["🤚"]?.convertToHandVectorMatcher(), let leftOKVector = okVector.left else { return } 替换不同手型，然而分数显示，还是只能识别出👌的手势，看了HandEmojiTotalJson.json中，已经有配置了这个手型。不知道是不是还有其他地方需要修改呢？

我这边测试是正常的。替换为"🤚"后，👌手势仍有 85 分左右，🤚手势有 97 分，分数更高一些。因为这两个手势有三根手指是一样的姿势，只有拇指和食指不一样，所以得分有一些相近。

**Comment by junpingfu** [comment]
哦哦，这个意思，明白了，谢谢🙏

**Comment by junpingfu** [comment]
请问下怎么关闭关节和手掌上的，白色小球啊｡°(°¯᷄◠¯᷅°)°｡

**Comment by XanderXu** [comment]
HandVectorTool.isSkeletonVisible
