### ISSUE TITLE
如何“录制”更多手势，并转化成json文件？

### ISSUE THREAD

**Issue by zlinoliver** [XanderXu/HandVector#3]
你好，请问下我要如何“录制”更多手势，即 捕获新手势的三维坐标数据， 并转化成json文件使用到项目中？比如🤟 的手势

**Comment by XanderXu** [comment]
你好，目前版本中，首先你需要开启手势追踪，将手部关节位置等信息保存在 **HandVectorMatcher** 中，然后直接使用 JSONEncoder 将其保存为 json 文件，也可以将其先转化为 HandEmojiParameter 或其它自定义对象，再用 JSONEncoder 保存。

JSONEncoder 的使用示例如下：
```swift
extension Encodable {
    func toJson(encoding: String.Encoding = .utf8) -> String? {
        guard let data = try? JSONEncoder().encode(self) else { return nil }
        return String(data: data, encoding: encoding)
    }
}
```

下个版本，我将对“录制”功能进行整理，添加到 Demo 中。

**Comment by zlinoliver** [comment]
感谢，我尝试下你的方法，我想支持其他手势，做机器人精准控制，还可以加到游戏丰富操控体验。期待你的“录制”功能demo。

**Comment by XanderXu** [comment]
你好，新版本 Demo 已发布，添加了录制和测试功能，并可以保存为 Json，欢迎使用 0.3.0 版本。

**Comment by zlinoliver** [comment]
辛苦大佬，我体验下
